# Generated by Django 3.1.6 on 2021-03-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Administrator',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='Appointment',
            new_name='date_time',
        ),
    ]
