# Generated by Django 3.1.6 on 2021-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appointment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
